export { default as Loader } from "./Loader";
export { default as Navbar } from "./Navbar";
export { default as Welcome } from "./Welcome";
export { default as Footer } from "./Footer";
export { default as Services } from "./Services";
export { default as Transactions } from "./Transactions";
export { default as About} from "./About";
export { default as TSC} from "./TSC";
export { default as Market} from "./Market";
export { default as Exchange} from "./Exchange";
export { default as ScrollToTop} from "./ScrollToTop";
